### ISSUE TITLE
Crash on Archlinux with ipfs 0.3.9

### ISSUE THREAD

**Issue by G-Ray** [ipfs-shipyard/station#106]
Installation process is fine. But any subsequent launch will output :

```
[geoffrey@ES1-Archlinux station]$ npm run electron

> ipfs-station@1.0.0-alpha.1 electron /home/geoffrey/git/station
> electron index.js

info: Booting
info: Application is ready
info: Starting tray
Uncaught SyntaxError: Unexpected token u
    at <error: TypeError: Cannot read property 'name' of undefined>
    at <error: TypeError: Cannot read property 'name' of undefined>
    at <error: TypeError: Cannot read property 'name' of undefined>
    at <error: TypeError: Cannot read property 'name' of undefined>
    at <error: TypeError: Cannot read property 'name' of undefined>
    at <error: TypeError: Cannot read property 'name' of undefined>
    at <error: TypeError: Cannot read property 'name' of undefined>
    at <error: TypeError: Cannot read property 'name' of undefined>
    at <error: TypeError: Cannot read property 'name' of undefined>
    at <error: TypeError: Cannot read property 'name' of undefined>
----------------------------------------
    at EventEmitter.on
    at makeWrappedCallback (/home/geoffrey/git/station/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
    at Request.object.(anonymous function) [as on] (/home/geoffrey/git/station/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
    at Request.init (/home/geoffrey/git/station/node_modules/request/request.js:201:10)
    at new Request (/home/geoffrey/git/station/node_modules/request/request.js:140:8)
    at request (/home/geoffrey/git/station/node_modules/request/index.js:55:10)
    at makeRequest (/home/geoffrey/git/station/node_modules/ipfs-api/src/request-api.js:80:10)
    at requestAPI (/home/geoffrey/git/station/node_modules/ipfs-api/src/request-api.js:129:5)
    at Object.get (/home/geoffrey/git/station/node_modules/ipfs-api/src/index.js:52:14)
    at _lookup (/home/geoffrey/git/station/node_modules/ipfs-geoip/lib/lookup.js:13:15)
    at conf.original (/home/geoffrey/git/station/node_modules/memoizee/ext/async.js:103:18)
----------------------------------------
    at EventEmitter.on
    at makeWrappedCallback (/home/geoffrey/git/station/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
    at Request.object.(anonymous function) [as on] (/home/geoffrey/git/station/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
    at Request.init (/home/geoffrey/git/station/node_modules/request/request.js:201:10)
    at new Request (/home/geoffrey/git/station/node_modules/request/request.js:140:8)
    at request (/home/geoffrey/git/station/node_modules/request/index.js:55:10)
    at makeRequest (/home/geoffrey/git/station/node_modules/ipfs-api/src/request-api.js:80:10)
    at requestAPI (/home/geoffrey/git/station/node_modules/ipfs-api/src/request-api.js:129:5)
    at IpfsAPI.self.id (/home/geoffrey/git/station/node_modules/ipfs-api/src/index.js:159:12)
    at pollStats (/home/geoffrey/git/station/build/init.js:62:8)
    at /home/geoffrey/git/station/build/init.js:103:5
----------------------------------------
    at EventEmitter.on
    at makeWrappedCallback (/home/geoffrey/git/station/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
    at Stream.object.(anonymous function) [as on] (/home/geoffrey/git/station/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
    at /home/geoffrey/git/station/node_modules/ipfsd-ctl/index.js:106:12
    at parseConfig (/home/geoffrey/git/station/node_modules/ipfsd-ctl/index.js:177:5)
    at Object.startDaemon (/home/geoffrey/git/station/node_modules/ipfsd-ctl/index.js:92:7)
    at onStartDaemon (/home/geoffrey/git/station/build/init.js:92:8)
    at EventEmitter.<anonymous> (/home/geoffrey/git/station/build/init.js:263:9)
    at EventEmitter.<anonymous> (/home/geoffrey/git/station/node_modules/long-stack-traces/lib/long-stack-traces.js:76:33)
    at emitNone (events.js:67:13)
    at EventEmitter.emit (events.js:166:7)
----------------------------------------
    at EventEmitter.on
    at makeWrappedCallback (/home/geoffrey/git/station/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
    at EventEmitter.object.(anonymous function) [as on] (/home/geoffrey/git/station/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
    at /home/geoffrey/git/station/build/init.js:241:8
    at Object.module.exports.local (/home/geoffrey/git/station/node_modules/ipfsd-ctl/index.js:198:5)
    at Object.boot (/home/geoffrey/git/station/build/init.js:236:25)
    at EventEmitter.<anonymous> (/home/geoffrey/git/station/node_modules/long-stack-traces/lib/long-stack-traces.js:76:33)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at Server.handleListening (/home/geoffrey/git/station/node_modules/monogamous/dist/monogamous.js:65:23)
    at Server.<anonymous> (/home/geoffrey/git/station/node_modules/long-stack-traces/lib/long-stack-traces.js:76:33)
----------------------------------------
    at EventEmitter.on
    at makeWrappedCallback (/home/geoffrey/git/station/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
    at EventEmitter.object.(anonymous function) [as on] (/home/geoffrey/git/station/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
    at Object.<anonymous> (/home/geoffrey/git/station/index.js:30:8)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Object.<anonymous> (/home/geoffrey/git/station/node_modules/electron-prebuilt/dist/resources/default_app/main.js:246:23)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
Uncaught undefined
Uncaught undefined
Uncaught undefined
error: Uncaught Exception:   undefined { '0': '' }
info: Shutting down application
info: Stopping daemon
info: Stopped daemon
info: Stopped daemon

npm ERR! Linux 4.2.5-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "electron"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! ipfs-station@1.0.0-alpha.1 electron: `electron index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ipfs-station@1.0.0-alpha.1 electron script 'electron index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ipfs-station package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ipfs-station
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/geoffrey/git/station/npm-debug.log
```

**Comment by Dignifiedquire** [comment]
@diasdavid looks like something in the api is not being parsed as it should be.

**Comment by Dignifiedquire** [comment]
I've done some updates, could you please try again with the latest version (make sure to run `npm install`  before you try)

**Comment by diasdavid** [comment]
@Dignifiedquire don't forget to upgrade to ipfs-api 2.7 :)

**Comment by G-Ray** [comment]
Thanks! This time I get :
```
[1] info: Booting
[1] info: Application is ready
[1] info: Starting tray
[1] info: Initialzing new node
[0] webpack built a3cd8a14a48f20f490d2 in 14778ms
[1] info: Initializing new node with key size: 4096 in /home/geoffrey/.ipfs.
[1] error: Uncaught Exception: Unexpected token u [SyntaxError: Unexpected token u] SyntaxError: Unexpected token u
[1]     at Object.parse (native)
[1]     at /home/geoffrey/git/station/node_modules/ipfs-geoip/lib/lookup.js:17:22
[1]     at Request._callback (/home/geoffrey/git/station/node_modules/ipfs-api/src/request-api.js:39:7)
[1]     at Request.self.callback (/home/geoffrey/git/station/node_modules/request/request.js:198:22)
[1]     at emitTwo (events.js:87:13)
[1]     at Request.emit (events.js:172:7)
[1]     at Request.<anonymous> (/home/geoffrey/git/station/node_modules/request/request.js:1082:10)
[1]     at emitOne (events.js:82:20)
[1]     at Request.emit (events.js:169:7)
[1]     at IncomingMessage.<anonymous> (/home/geoffrey/git/station/node_modules/request/request.js:1009:12) { '0': [SyntaxError: Unexpected token u] }
[1] info: Shutting down application
[1] info: Stopping daemon
[1] info: Stopped daemon
[1] info: Stopped daemon
```

**Comment by Dignifiedquire** [comment]
Can you please try out the latest master and let me know if this still happens?

**Comment by fazo96** [comment]
It works for me on latest Arch Linux, running latest `master` using `npm start`

Log:

```bash
fazo@ape|~/Documenti/Git/station on master
❯❯❯ npm start

> ipfs-station@1.0.0-alpha.1 prestart /home/fazo/Documenti/Git/station
> npm run clean && npm run build:babel


> ipfs-station@1.0.0-alpha.1 clean /home/fazo/Documenti/Git/station
> rimraf build && mkdir build


> ipfs-station@1.0.0-alpha.1 build:babel /home/fazo/Documenti/Git/station
> babel app/config.js -o build/config.js && babel app/controls -d build/controls && babel app/init.js -o build/init.js

app/controls/drag-drop.js -> build/controls/drag-drop.js
app/controls/open-browser.js -> build/controls/open-browser.js
app/controls/open-console.js -> build/controls/open-console.js
app/controls/open-settings.js -> build/controls/open-settings.js
app/controls/utils.js -> build/controls/utils.js

> ipfs-station@1.0.0-alpha.1 start /home/fazo/Documenti/Git/station
> concurrent --kill-others 'node dev-server.js' 'npm run electron'

[0] Development server started at http://localhost:3000
[1] 
[1] > ipfs-station@1.0.0-alpha.1 electron /home/fazo/Documenti/Git/station
[1] > electron index.js
[1] 
[1] info: Application is ready
[1] info: Starting tray
[0] webpack built 97f90ccf0823c1721817 in 2430ms
```

**Comment by diasdavid** [comment]
@G-Ray mind giving this another try? So many things have been updated :)

**Comment by G-Ray** [comment]
Sorry @diasdavid I'm not using Arch anymore

**Comment by diasdavid** [comment]
closing this one then. Thanks! :)
